catsapp/cats/urls.py
from django.conf.urls import url

from . import views

# namespace urls
app_name = 'cats'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'new/$', views.new_cat, name='new'),
]

catsapp/catsapp/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^cats/', include('cats.urls')),
    url(r'^admin/', admin.site.urls),
]

catsapp/cats/models.py
from django.db import models

class Cat(models.Model):
    name = models.CharField(max_length=255)
    year_of_birth = models.IntegerField()

    def __str__(self):
        return 'Cat: ' + self.name

catsapp/cats/views.py
from django.shortcuts import render, redirect
from datetime import datetime

from .models import Cat

def index(request):
    cat_list = Cat.objects.all()
    context = {
        'cat_list': cat_list
    }
    return render(request, 'cats/index.html', context)

def new_cat(request):
    context = {}

    form = {
        'name': '',
        'year_of_birth': '',
        'errors': {}
    }

    context['form'] = form

    if request.method == 'POST':
        form['name'] = request.POST['name']
        form['year_of_birth'] = request.POST['year_of_birth']

        validate_cat(form)

        if not form['errors']:
            c = Cat(
                name=form['name'],
                year_of_birth=form['year_of_birth']
            )
            c.save()
            return redirect(to='cats:index')

    return render(request, 'cats/new_cat.html', context)

def validate_cat(form):
    if not form['name']:
        form['errors']['name'] = 'This field is required'

    if not form['year_of_birth']:
        form['errors']['year_of_birth'] = 'This field is required'

    try:
        form['year_of_birth'] = int(form['year_of_birth'])

        if form['year_of_birth'] < 1900 or form['year_of_birth'] > datetime.now().year:
            form['errors']['year_of_birth'] = 'You must enter a valid year'
    except ValueError:
        form['errors']['year_of_birth'] = 'You must enter a number'

catsapp/cats/templates/cats/base.html
<html>
    <head>
        <title>Cats</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
    </head>
    <body>

        <div class="container">
            <nav class="navbar navbar-default">
                <div class="container-fluid">
                  <div class="navbar-header">
                    <a class="navbar-brand" href="{% url 'cats:index' %}">Cats</a>
                  </div>
                  <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        {% block nav %}
                        {% endblock nav %}
                    </ul>
                  </div><!--/.nav-collapse -->
                </div><!--/.container-fluid -->
              </nav>
            {% block main %}
            {% endblock main %}
        </div>
    </body>
</html>

catsapp/cats/templates/cats/index.html
{% extends "cats/base.html" %}

{% block nav %}
  <li class="active"><a href="{% url 'cats:index' %}">Cats</a></li>
  <li><a href="{% url 'cats:new' %}">New cat</a></li>
{% endblock nav %}

{% block main %}
    <div class="row">
        <div class="col-md-12">
            <h3>Cats</h3>
            {% if cat_list %}
                {% for cat in cat_list %}
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <div>Name: {{cat.name}}</div>
                            <div>Year of Birth: {{cat.year_of_birth}}</div>
                        </div>
                    </div>
                {% endfor %}
            {% endif %}
        </div>
    </div>
{% endblock main %}

catsapp/cats/templates/cats/new_cat.html
{% extends "cats/base.html" %}

{% block nav %}
  <li><a href="{% url 'cats:index' %}">Cats</a></li>
  <li class="active"><a href="{% url 'cats:new' %}">New cat</a></li>
{% endblock nav %}

{% block main %}
    <div class="row">
        <div class="col-md-12">
            <h3>New cat</h3>
            <form action="{% url 'cats:new' %}" method="post">
                {% csrf_token %}
                <div class="form-group {% if form.errors.name %}has-error{% endif %}">
                    <label for="name">Name</label>
                    <input class="form-control"
                           id="name"
                           name="name"
                           type="text"
                           value="{{ form.name }}"/>
                    <span class="help-block">{{ form.errors.name }}</span>
                </div>
                <div class="form-group {% if form.errors.year_of_birth %}has-error{% endif %}">
                    <label for="year_of_birth">Year of Birth</label>
                    <input class="form-control"
                           id="year_of_birth"
                           name="year_of_birth"
                           type="text"
                           value="{{ form.year_of_birth }}">
                    <span class="help-block">{{ form.errors.year_of_birth }}</span>
                </div>
                <div class="btn-group">
                    <input class="btn btn-submit" type="submit" value="Create">
                </div>
            </form>
        </div>
    </div>
{% endblock main %}